### ISSUE TITLE
Failing to call anonymous methods

### ISSUE THREAD

**Issue by aimanicose4** [adobe/acc-js-sdk#96]
Hi Team,  
I'm facing an issue calling anonymous methods. Normal behavior through  SOAP call would allow for an anonymous method to be called without any authentification. 
Through the SDK though, this behavior is not possible through anonymous logon. An "Access Forbidden" error is sent when making the call since the method "xtk:persist#GetEntityIfMoreRecent" is being called before every request which requires authentication.

Is it possible to fix this issue if it is within the intended purposes of the anonymous logon, otherwise is there a turnaround ? 

Thank you.

**Comment by mkiki** [comment]
Hi @aimanicose4, I'd like to understand the issue better.

I'm not aware of any anonymous SOAP methods in Campaign, but maybe I'm wrong. Do you have a more specific example? Is there a particular SOAP method you'd like to call anonymously? Is it a custom SOAP method? Could you share some sample code which illustrate the issue?

My guess is that indeed, in order to call any SOAP API, the SDK needs to lookup the corresponding schema, from which it will get the SOAP method definition. This is done via the GetEntityIfMoreRecent call, which indeed, requires authentication.

If you can provide a simple example, I can look for a solution.

**Comment by aimanicose4** [comment]
Hello @mkiki , Thank you for you response.

The particular SOAP method i'd like to call anonymously is indeed a custom one I created in ACC. I basically want to create a method to bypass the standard adobe campaign logon method and have a sort of sigle sign on system for our front end application that communicates with ACC through a nodeJS server. 

The method declaration looks like this (with a custom implementation to handle sign on): 
![image](https://github.com/adobe/acc-js-sdk/assets/121268026/9bc74122-9a72-42ae-893e-5bff3a0815a3)

After creating the method, I managed to call it successfully through SOAP API using Postman without any authentication method. But couldn't reproduce the same behavior through SDK.

I actually managed to "make it work" yesterday by mingling a little bit in the SDK code and changing the behavior of AnonymousUser authentication like this : 

![image](https://github.com/adobe/acc-js-sdk/assets/121268026/71e12f81-058a-41d0-ac24-e694078ce187)

And calling my customized anonymous method directly using ofAnonymousUser connection. But as you know this is a very use case specific change and is not sustainable to change the code after each update to the sdk.

**Comment by mkiki** [comment]
Hi @aimanicose4, I understand better now. Implementing custom auth mechansim is tricky. I'm not sure it can actually be done in a secure way. 

In recent versions of Campaign, we have improved our support for IMS authentication, and maybe it's possible to use IMS federated id to achieve secure SSO. Unfortunately, I'm not familiar with all the details, but the basic id is that Adobe IMS Federated id service can securely delegate authentication to your identity provider, and will provide you IMS bearer tokens that are compatible with ACC. But you'll probably need a fairly recent version of ACC for this (8.5 or above). Give me a couple of days to find out more, but I think it's probably the best long term sustainable and secure way to achieve what you want.

Now, in the short term, I can think of 2 approaches and 2 use cases:
1/ ability to call anonymous SOAP methods (independently of the login policy)
2/ provide a supported way in the SDK for custom login schemes. I'm a bit reluctant to this, because I do not believe it's feasible to guarantee security with custom login schemes.

I'll have to do some research and run some tests to implement 1/ I thinks this should solve your use case.

**Comment by aimanicose4** [comment]
Hi @mkiki , Thank you so much for your help.

I sadly don't think IMS authentication would solve my issue even if I were on >=8.5 since my front end application is bound to my company's own authentication protocol so I'm kinda forced to work around it.

I also believe 1/ would help solve the issue for now. 


Thanks once again.

**Comment by aimanicose4** [comment]
This seems like a perfect solution to me. 

Thank you so much @mkiki  for your quick response.

**Comment by aimanicose4** [comment]
Thank you !
